-- =============================================
-- Tabla de Turnos (Shifts) - Horarios Generados
-- =============================================
-- Un turno representa un conjunto de viajes generados para una ruta en una fecha específica

-- Secuencia para id_shift
CREATE SEQUENCE IF NOT EXISTS seq_shifts_id START 1;

-- Tabla principal de turnos
CREATE TABLE IF NOT EXISTS tab_plans(
    id_plan         INTEGER         GENERATED BY DEFAULT AS IDENTITY,   -- ID único del turno
    id_route        DECIMAL(3,0)    NOT NULL,                           -- FK a tab_routes
    plan_date       DATE            NOT NULL,                           -- Fecha del turno
    start_time      TIME            NOT NULL,                           -- Hora inicio del turno
    end_time        TIME            NOT NULL,                           -- Hora fin del turno
    frequency       DECIMAL(3,0)    NOT NULL DEFAULT 15,               -- Frecuencia en minutos
    --plan_duration  INTEGER         NOT NULL,                          -- Duración de cada viaje en minutos
    total_rounds    INTEGER         NOT NULL DEFAULT 0,                 -- Total de viajes generados
    assigned_rounds INTEGER         NOT NULL DEFAULT 0,                 -- Viajes con bus asignado
    status_shift    VARCHAR(20)     NOT NULL DEFAULT 'draft',           -- Estado: draft, active, completed, cancelled
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    user_create     VARCHAR(100)    NOT NULL,
    user_update     VARCHAR(100),
    
    -- Constraints
    CONSTRAINT pk_plans PRIMARY KEY (id_plan),
    CONSTRAINT fk_shifts_route FOREIGN KEY (id_route) REFERENCES tab_routes(id_route) ON DELETE CASCADE,
    CONSTRAINT uk_shifts_route_date UNIQUE (id_route, shift_date, start_time),  -- No duplicar turno mismo día/hora
    CONSTRAINT chk_shifts_status CHECK (status_shift IN ('draft', 'active', 'completed', 'cancelled')),
    CONSTRAINT chk_shifts_times CHECK (end_time > start_time),
    CONSTRAINT chk_shifts_frequency CHECK (frequency_min BETWEEN 1 AND 120),
    CONSTRAINT chk_shifts_duration CHECK (trip_duration BETWEEN 5 AND 480)
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_shifts_route ON tab_shifts(id_route);
CREATE INDEX IF NOT EXISTS idx_shifts_date ON tab_shifts(shift_date);
CREATE INDEX IF NOT EXISTS idx_shifts_status ON tab_shifts(status_shift);
CREATE INDEX IF NOT EXISTS idx_shifts_route_date ON tab_shifts(id_route, shift_date);


-- =============================================
-- Tabla de Viajes del Turno (Shift Trips)
-- =============================================
-- Cada viaje individual dentro de un turno

CREATE TABLE IF NOT EXISTS tab_shift_trips (
    id_shift_trip   INTEGER         GENERATED BY DEFAULT AS IDENTITY,   -- ID único del viaje
    id_shift        INTEGER         NOT NULL,                           -- FK al turno padre
    plate_number    VARCHAR(6),                                         -- FK al bus asignado (NULL si no asignado)
    trip_order      INTEGER         NOT NULL,                           -- Orden del viaje en el turno (1, 2, 3...)
    scheduled_start TIME            NOT NULL,                           -- Hora inicio programada
    scheduled_end   TIME            NOT NULL,                           -- Hora fin programada
    actual_start    TIMESTAMPTZ,                                        -- Hora inicio real
    actual_end      TIMESTAMPTZ,                                        -- Hora fin real
    status_trip     VARCHAR(20)     NOT NULL DEFAULT 'pending',         -- Estado del viaje
    batch_number    INTEGER         NOT NULL DEFAULT 1,                 -- Número de recorrido/lote
    notes           TEXT,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    
    -- Constraints
    CONSTRAINT pk_shift_trips PRIMARY KEY (id_shift_trip),
    CONSTRAINT fk_shift_trips_shift FOREIGN KEY (id_shift) REFERENCES tab_shifts(id_shift) ON DELETE CASCADE,
    CONSTRAINT fk_shift_trips_bus FOREIGN KEY (plate_number) REFERENCES tab_buses(plate_number) ON DELETE SET NULL,
    CONSTRAINT uk_shift_trips_order UNIQUE (id_shift, trip_order, batch_number),
    CONSTRAINT chk_shift_trips_status CHECK (status_trip IN ('pending', 'assigned', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT chk_shift_trips_times CHECK (scheduled_end > scheduled_start)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_shift_trips_shift ON tab_shift_trips(id_shift);
CREATE INDEX IF NOT EXISTS idx_shift_trips_bus ON tab_shift_trips(plate_number);
CREATE INDEX IF NOT EXISTS idx_shift_trips_status ON tab_shift_trips(status_trip);
CREATE INDEX IF NOT EXISTS idx_shift_trips_batch ON tab_shift_trips(id_shift, batch_number);


-- =============================================
-- Función: Actualizar contadores del turno
-- =============================================
CREATE OR REPLACE FUNCTION fn_update_shift_counters()
RETURNS TRIGGER AS $$
BEGIN
    -- Actualizar total_trips y assigned_trips en tab_shifts
    UPDATE tab_shifts
    SET 
        total_trips = (
            SELECT COUNT(*) FROM tab_shift_trips WHERE id_shift = COALESCE(NEW.id_shift, OLD.id_shift)
        ),
        assigned_trips = (
            SELECT COUNT(*) FROM tab_shift_trips 
            WHERE id_shift = COALESCE(NEW.id_shift, OLD.id_shift) 
            AND plate_number IS NOT NULL
        ),
        updated_at = NOW()
    WHERE id_shift = COALESCE(NEW.id_shift, OLD.id_shift);
    
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Trigger para actualizar contadores
DROP TRIGGER IF EXISTS trg_update_shift_counters ON tab_shift_trips;
CREATE TRIGGER trg_update_shift_counters
AFTER INSERT OR UPDATE OR DELETE ON tab_shift_trips
FOR EACH ROW
EXECUTE FUNCTION fn_update_shift_counters();


-- =============================================
-- Función: Crear turno con viajes
-- =============================================
CREATE OR REPLACE FUNCTION fun_create_shift(
    p_id_route      DECIMAL(3,0),
    p_shift_date    DATE,
    p_start_time    TIME,
    p_end_time      TIME,
    p_frequency     INTEGER,
    p_duration      INTEGER,
    p_user          VARCHAR(100),
    OUT success     BOOLEAN,
    OUT msg         TEXT,
    OUT id_shift    INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_time  TIME;
    v_trip_end      TIME;
    v_trip_order    INTEGER := 0;
BEGIN
    -- Validaciones
    IF p_end_time <= p_start_time THEN
        success := FALSE;
        msg := 'La hora de fin debe ser posterior a la hora de inicio';
        RETURN;
    END IF;
    
    IF p_frequency <= 0 OR p_duration <= 0 THEN
        success := FALSE;
        msg := 'La frecuencia y duración deben ser mayores a 0';
        RETURN;
    END IF;
    
    -- Verificar que la ruta existe
    IF NOT EXISTS (SELECT 1 FROM tab_routes WHERE id_route = p_id_route) THEN
        success := FALSE;
        msg := 'La ruta especificada no existe';
        RETURN;
    END IF;
    
    -- Verificar que no existe un turno igual
    IF EXISTS (
        SELECT 1 FROM tab_shifts 
        WHERE id_route = p_id_route 
        AND shift_date = p_shift_date 
        AND start_time = p_start_time
    ) THEN
        success := FALSE;
        msg := 'Ya existe un turno para esta ruta en la misma fecha y hora';
        RETURN;
    END IF;
    
    -- Crear el turno
    INSERT INTO tab_shifts (
        id_route, shift_date, start_time, end_time, 
        frequency_min, trip_duration, status_shift, user_create
    )
    VALUES (
        p_id_route, p_shift_date, p_start_time, p_end_time,
        p_frequency, p_duration, 'draft', p_user
    )
    RETURNING tab_shifts.id_shift INTO id_shift;
    
    -- Generar los viajes
    v_current_time := p_start_time;
    
    WHILE v_current_time <= p_end_time LOOP
        v_trip_order := v_trip_order + 1;
        v_trip_end := v_current_time + (p_duration || ' minutes')::INTERVAL;
        
        INSERT INTO tab_shift_trips (
            id_shift, trip_order, scheduled_start, scheduled_end, status_trip
        )
        VALUES (
            id_shift, v_trip_order, v_current_time, v_trip_end::TIME, 'pending'
        );
        
        v_current_time := v_current_time + (p_frequency || ' minutes')::INTERVAL;
    END LOOP;
    
    success := TRUE;
    msg := 'Turno creado con ' || v_trip_order || ' viajes';
    
EXCEPTION
    WHEN OTHERS THEN
        success := FALSE;
        msg := 'Error al crear turno: ' || SQLERRM;
        id_shift := NULL;
END;
$$;


-- =============================================
-- Función: Asignar bus a viaje del turno
-- =============================================
CREATE OR REPLACE FUNCTION fun_assign_bus_to_trip(
    p_id_shift_trip INTEGER,
    p_plate_number  VARCHAR(6),
    OUT success     BOOLEAN,
    OUT msg         TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    -- Verificar que el viaje existe
    IF NOT EXISTS (SELECT 1 FROM tab_shift_trips WHERE id_shift_trip = p_id_shift_trip) THEN
        success := FALSE;
        msg := 'El viaje especificado no existe';
        RETURN;
    END IF;
    
    -- Verificar que el bus existe y está activo
    IF p_plate_number IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM tab_buses WHERE plate_number = p_plate_number AND is_active = TRUE
    ) THEN
        success := FALSE;
        msg := 'El bus especificado no existe o no está activo';
        RETURN;
    END IF;
    
    -- Asignar o desasignar el bus
    UPDATE tab_shift_trips
    SET 
        plate_number = p_plate_number,
        status_trip = CASE WHEN p_plate_number IS NOT NULL THEN 'assigned' ELSE 'pending' END,
        updated_at = NOW()
    WHERE id_shift_trip = p_id_shift_trip;
    
    success := TRUE;
    IF p_plate_number IS NOT NULL THEN
        msg := 'Bus asignado correctamente al viaje';
    ELSE
        msg := 'Bus desasignado del viaje';
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        success := FALSE;
        msg := 'Error: ' || SQLERRM;
END;
$$;


-- =============================================
-- Vista: Resumen de turnos por ruta y fecha
-- =============================================
CREATE OR REPLACE VIEW vw_shifts_summary AS
SELECT 
    s.id_shift,
    s.id_route,
    r.name_route,
    r.color_route,
    s.shift_date,
    s.start_time,
    s.end_time,
    s.frequency_min,
    s.trip_duration,
    s.total_trips,
    s.assigned_trips,
    s.total_trips - s.assigned_trips AS pending_trips,
    CASE 
        WHEN s.total_trips = 0 THEN 0
        ELSE ROUND((s.assigned_trips::NUMERIC / s.total_trips) * 100, 1)
    END AS assignment_percentage,
    s.status_shift,
    s.created_at
FROM tab_shifts s
JOIN tab_routes r ON s.id_route = r.id_route
ORDER BY s.shift_date DESC, s.start_time;


-- =============================================
-- Vista: Detalle de viajes con información
-- =============================================
CREATE OR REPLACE VIEW vw_shift_trips_detail AS
SELECT 
    st.id_shift_trip,
    st.id_shift,
    s.shift_date,
    s.id_route,
    r.name_route,
    st.trip_order,
    st.batch_number,
    st.scheduled_start,
    st.scheduled_end,
    st.plate_number,
    b.amb_code,
    d.name_driver,
    st.status_trip,
    st.actual_start,
    st.actual_end
FROM tab_shift_trips st
JOIN tab_shifts s ON st.id_shift = s.id_shift
JOIN tab_routes r ON s.id_route = r.id_route
LEFT JOIN tab_buses b ON st.plate_number = b.plate_number
LEFT JOIN tab_drivers d ON b.id_driver = d.id_driver
ORDER BY s.shift_date, st.id_shift, st.batch_number, st.trip_order;
